export const preguntas = [
  [
    {
      //nivel  1
      categoria : "Cultura General",
      nivel : 1,
      pregunta : "Cuál es el idioma oficial de Brasil?",
      "1": "Brasilero",
      "2": "Italiano",
      "3": "Portugues",
      "4": "Frances",
      respuesta: "3",
    },
    {
      categoria : "Deportes",
      nivel : 1,
      pregunta : "Cada cuántos años se realizan los Juegos Olímpicos?",
      "1": "3 años",
      "2": "6 años",
      "3": "5 años",
      "4": "4 años",
      respuesta: "4",
    },
    {
      categoria : "Geografia",
      nivel : 1,
      pregunta : "Cuál es la capital de El Salvador?",
      "1": "Managua",
      "2": "San Jose",
      "3": "San Salvador",
      "4": "Tegucigalpa",
      respuesta: "3",
    },
    {
      categoria : "Ciencia",
      nivel : 1,
      pregunta : "Cuál es el cuarto planeta del sistema solar?",
      "1": "Tierra",
      "2": "Mercurio",
      "3": "Venus",
      "4": "Marte",
      respuesta: "4",
    },
    {
      categoria : "Arte",
      nivel : 1,
      pregunta : 'Quién escribió "Cien años de soledad"?',
      "1": "Rafael Pombo",
      "2": "José Eustasio Rivera",
      "3": "Jorge Isaacs",
      "4": "Gabriel García Márquez",
      respuesta: "4",
    },
  ],
  [
    {
      // nivel  2
      categoria : "Cultura General",
      nivel : 2,
      pregunta : "El origen del café proviene de...",
      "1": "Etiopía",
      "2": "Egipto",
      "3": "Indonesia",
      "4": "Corea",
      respuesta: "2",
    },
    {
      categoria : "Deportes",
      nivel : 2,
      pregunta :
        "Qué jugador de fútbol ha ganado más copas del mundo junto a su equipo?",
      "1": "Messi",
      "2": "Pelé",
      "3": "Maradona",
      "4": "Cristiano Ronaldo",
      respuesta: "2",
    },
    {
      categoria : "Geografia",
      nivel : 2,
      pregunta : "Cuál es la montaña mas alta del mundo?",
      "1": "K2",
      "2": "Kanchenjunga",
      "3": "Manaslu",
      "4": "Everest",
      respuesta: "4",
    },
    {
      categoria : "Ciencia",
      nivel : 2,
      pregunta : "Cuál es el elemento más abundante de la Tierra?",
      "1": "Oxigeno",
      "2": "Carbono",
      "3": "Hidrógeno",
      "4": "Potasio",
      respuesta: "3",
    },
    {
      categoria : "Arte",
      nivel : 2,
      pregunta : "Cuál fue la primera película que apareció de Disney?",
      "1": "Blancanieves",
      "2": "La bella y la bestia",
      "3": "Pinocho",
      "4": "Fantasía",
      respuesta: "1",
    },
  ],
  [
    {
      //nivel  3
      categoria : "Cultura General",
      nivel : 3,
      pregunta : "En que año se fundó la franquicia de comida rápida McDonalds?",
      "1": "1945",
      "2": "1940",
      "3": "1954",
      "4": "1947",
      respuesta: "a",
    },
    {
      categoria : "Deportes",
      nivel : 3,
      pregunta : "Qué animal es la mascota del Giro de Italia? ",
      "1": "Perro",
      "2": "Zorro",
      "3": "Alce",
      "4": "Lobo",
      respuesta: "4",
    },
    {
      categoria : "Geografia",
      nivel : 3,
      pregunta : "Cuál es la capital de Marruecos?",
      "1": "Rabat",
      "2": "Kiev",
      "3": "Varsovia",
      "4": "Moscú",
      respuesta: "1",
    },
    {
      categoria : "Ciencia",
      nivel : 3,
      pregunta :
        "Cómo se llama la unidad de intensidad de la corriente eléctrica?",
      "1": "Voltio",
      "2": "Amperio",
      "3": "Ohmio",
      "4": "Vatio",
      respuesta: "2",
    },
    {
      categoria : "Arte",
      nivel : 3,
      pregunta : "Dónde nació el escritor Julio Cortázar?",
      "1": "Uruguay",
      "2": "Argentina",
      "3": "Perú",
      "4": "Ecuador",
      respuesta: "2",
    },
  ],
  [
    {
      //nivel  4
      categoria : "Cultura General",
      nivel : 4,
      pregunta :
        "Qué enfermedad tenía el legendario astrofísico Stephen Hawking?",
      "1": "Enfermedad de Addison",
      "2": "Progeria de Hutchinson-Gilford",
      "3": "Síndrome de Marfan",
      "4": "Esclerosis Lateral Amiotrófica",
      respuesta: "4",
    },
    {
      categoria : "Deportes",
      nivel : 4,
      pregunta : "Cuál es el deporte en el que destacó Carl Lewis?",
      "1": "Atletismo",
      "2": "Gimnasia",
      "3": "Natación",
      "4": "Tenis",
      respuesta: "1",
    },
    {
      categoria : "Geografia",
      nivel : 4,
      pregunta : "En qué pais se encuentra el rio Po?",
      "1": "Francia",
      "2": "España",
      "3": "Portugal",
      "4": "Italia",
      respuesta: "4",
    },
    {
      categoria : "Ciencia",
      nivel : 4,
      pregunta : "Dónde están ubicados los huesos escafoides?",
      "1": "Cadera",
      "2": "Muñeca",
      "3": "Rodilla",
      "4": "pie",
      respuesta: "2",
    },
    {
      categoria : "Arte",
      nivel : 4,
      pregunta : "Quién es el director de la película Big Fish?",
      "1": "Peter Jackson",
      "2": "Steven Spielberg",
      "3": "Tim Burton",
      "4": "Christopher Nolan",
      respuesta: "3",
    },
  ],
  [
    {
      // nivel  5
      categoria : "Cultura General",
      nivel : 5,
      pregunta :
        "Qué trilogía de las películas basadas en los cómics de Marvel recaudó más dinero en taquilla?",
      "1": "Iron Man",
      "2": "Wolverine",
      "3": "Capitán América",
      "4": "Thor",
      respuesta: "3",
    },
    {
      categoria : "Deportes",
      nivel : 5,
      pregunta :
        "Cómo se llamaba el ciclista italiano apodado 'Il campionissimo'?",
      "1": "Fausto Coppi",
      "2": "Valerio Agnoli",
      "3": "Enrico Battaglin",
      "4": "Claudio Bortolotto",
      respuesta: "1",
    },
    {
      categoria : "Geografia",
      nivel : 5,
      pregunta : "Cuál es la capital de Kazajistán?",
      "1": "Astaná",
      "2": "Taraz",
      "3": "Semey",
      "4": "Almatý",
      respuesta: "1",
    },
    {
      categoria : "Ciencia",
      nivel : 5,
      pregunta : "Qué distancia hay de la Tierra al Sol?",
      1: "Astaná",
      2: "Taraz",
      3: "Semey",
      4: "Almatý",
      respuesta: "1",
    },
    {
      categoria : "Arte",
      nivel : 5,
      pregunta : "En qué año se celebró el festival de Woodstock?",
      "1": "1970",
      "2": "1969",
      "3": "1955",
      "4": "1976",
      respuesta: "2",
    },
  ],
];
